version: "3"
services:
  api_server:
    env_file:
      .env
    build: .

    environment:
      TZ: Europe/Moscow

    command: sh -c "pnpm start"
    ports:
      - "5100:3040"
    restart: unless-stopped