version: "3"
services:
  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api_server:
    env_file:
      .env
    build: .

    environment:
      TZ: Europe/Moscow

    command: sh -c "pnpm start"
    ports:
      - "5100:3040"
    restart: unless-stopped

    healthcheck:
      test: wget -S -O- http://api_server:3040/health-api/health || exit 1
      interval: 5m
      timeout: 5m
      retries: 3

  reduce_prover:
    env_file:
      .env
    build: .

    environment:
      TZ: Europe/Moscow

    command: sh -c "pnpm start-rp"
    restart: unless-stopped
  
    healthcheck:
      test: wget -S -O- http://api_server:3042/health-api/health || exit 1
      interval: 5m
      timeout: 5m
      retries: 3


  distribution_prover:
    env_file:
      .env
    build: .

    environment:
      TZ: Europe/Moscow

    command: sh -c "pnpm start-dp"
    restart: unless-stopped
    healthcheck:
      test: wget -S -O- http://api_server:3041/health-api/health || exit 1
      interval: 5m
      timeout: 5m
      retries: 3
