version: "3"
services:
  api_server:
    env_file:
      .env
    build: .

    environment:
      TZ: Europe/Moscow

    command: sh -c "pnpm start"
    ports:
      - "5100:3040"
    restart: always

    healthcheck:
      test: wget -S -O- http://api_server:3040/claim-api/health || exit 1
      interval: 10s
      timeout: 30s
      retries: 3
